# Generated by Django 3.2.16 on 2022-12-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='pruduct',
            new_name='product',
        ),
    ]
